# Create/Delete network and firewall rules based on oo_network_state
#
# We have to parameterize Create/Destroy tasks because you can't delete a
# network with rules currently assigned becuase it considers it "in use"
- name: Create network
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    ipv4_range: "{{ oo_network_range }}"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "present"

- name: Create/configure firewall rule - Allow Internal TCP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    fwname: "{{ oo_network }}-allow-internal"
    src_range: "{{ oo_network_range }}"
    allowed: 'tcp:1-65535'
    state: "{{ oo_network_state }}"
  when: oo_network_state == "present"

- name: Delete firewall rule - Allow Internal TCP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ oo_network }}-allow-internal"
    src_range: "{{ oo_network_range }}"
    allowed: 'tcp:1-65535'
    state: "{{ oo_network_state }}"
  when: oo_network_state == "deleted"

- name: Create/Configure firewall rule - Allow Internal UDP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    fwname: "{{ oo_network }}-allow-internal"
    src_range: "{{ oo_network_range }}"
    allowed: 'udp:1-65535'
    state: "{{ oo_network_state }}"
  when: oo_network_state == "present"

- name: Delete firewall rule - Allow Internal UDP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ oo_network }}-allow-internal"
    src_range: "{{ oo_network_range }}"
    allowed: 'udp:1-65535'
    state: "{{ oo_network_state }}"
  when: oo_network_state == "deleted"

- name: Create/Configure firewall rule - Allow Internal ICMP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    fwname: "{{ oo_network }}-allow-internal"
    src_range: "{{ oo_network_range }}"
    allowed: 'tcp:1-65535'
    state: "{{ oo_network_state }}"
  when: oo_network_state == "present"

- name: Delete firewall rule - Allow Internal ICMP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ oo_network }}-allow-internal"
    src_range: "{{ oo_network_range }}"
    allowed: 'tcp:1-65535'
    state: "{{ oo_network_state }}"
  when: oo_network_state == "deleted"

- name: Create/Configure firewall rule - Allow SSH
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    fwname: "{{ oo_network }}-allow-ssh"
    allowed: "tcp:22"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "present"

- name: Delete firewall rule - Allow SSH
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ oo_network }}-allow-ssh"
    allowed: "tcp:22"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "deleted"

- name: Create/Configure firewall rule - Allow HTTP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    fwname: "{{ oo_network }}-allow-http"
    allowed: "tcp:80"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "present"

- name: Create/Configure firewall rule - Allow HTTP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ oo_network }}-allow-http"
    allowed: "tcp:80"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "deleted"

- name: Create/Configure firewall rule - Allow HTTPS
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    fwname: "{{ oo_network }}-allow-https"
    allowed: "tcp:443"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "present"

- name: Delete firewall rule - Allow HTTPS
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ oo_network }}-allow-https"
    allowed: "tcp:443"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "deleted"

- name: Create/Configure firewall rule - Allow ICMP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    fwname: "{{ oo_network }}-allow-icmp"
    allowed: "icmp"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "present"

- name: Delete firewall rule - Allow ICMP
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ oo_network }}-allow-icmp"
    allowed: "icmp"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "deleted"

- name: Terminate network
  gce_net:
    service_account_email: "{{ gce_service_account_email }}"
    pem_file: "{{ gce_pem_file }}"
    project_id: "{{ gce_project_id }}"
    name: "{{ oo_network }}"
    ipv4_range: "{{ oo_network_range }}"
    state: "{{ oo_network_state }}"
  when: oo_network_state == "deleted"
